### ISSUE TITLE
Slice bounds out of range panic in v8.15.2-v8.16.1

### ISSUE THREAD

**Issue by agmond** [gitleaks/gitleaks#1132]
When running v8.15.2, I get this error:
```
panic: runtime error: slice bounds out of range [31:28]

goroutine 189 [running]:
github.com/zricethezav/gitleaks/v8/detect.printFinding({{0xc0002d9930, 0xf}, 0xd6, 0xd6, 0x16, 0x4b, {0xc0000241c1, 0x1c}, {0xc000024220, 0x1f}, ...})
	/go/src/github.com/zricethezav/gitleaks/detect/utils.go:125 +0x14cd
github.com/zricethezav/gitleaks/v8/detect.(*Detector).addFinding(_, {{0xc0002d9930, 0xf}, 0xd6, 0xd6, 0x16, 0x4b, {0xc0000241c0, 0x1d}, {0xc000024220, ...}, ...})
	/go/src/github.com/zricethezav/gitleaks/detect/detect.go:579 +0x3e5
github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles.func2()
	/go/src/github.com/zricethezav/gitleaks/detect/detect.go:469 +0x305
github.com/fatih/semgroup.(*Group).Go.func1()
	/go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0xa2
created by github.com/fatih/semgroup.(*Group).Go
	/go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x25b
```

This is the command I used:
```
gitleaks detect --config <CONFIG_FILE_PATH> --source . -v --report-format json --report-path <REPORT_FILE> --redact --no-git --exit-code 0
```

I upgraded to v8.16.1 and it didn't solve the problem.

cc @zricethezav

**Comment by agmond** [comment]
Hi @zricethezav, thanks for the quick response.
Currently I don't have a sample file or repo that reproduces this issue.
I'll update here if I put my hands on such.

**Comment by agmond** [comment]
Thanks for the fix, @zricethezav!

When do you plan to issue a new release that includes this fix?

**Comment by zricethezav** [comment]
@agmond https://github.com/gitleaks/gitleaks/releases/tag/v8.16.2 released! Let me know if that fixes the problem, if not we can reopen this issue.

**Comment by agmond** [comment]
Hi @zricethezav,
It seems that the issue is not solved yet.
Here's what I see now:
```
panic: runtime error: slice bounds out of range [31:28]

goroutine 185 [running]:
github.com/zricethezav/gitleaks/v8/detect.printFinding({{0xc0003b5b50, 0xf}, 0xd6, 0xd6, 0x16, 0x4b, {0xc00079b421, 0x1c}, {0xc00079b440, 0x1f}, ...}, ...)
	/go/src/github.com/zricethezav/gitleaks/detect/utils.go:131 +0x1575
github.com/zricethezav/gitleaks/v8/detect.(*Detector).addFinding(_, {{0xc0003b5b50, 0xf}, 0xd6, 0xd6, 0x16, 0x4b, {0xc00079b420, 0x1d}, {0xc00079b440, ...}, ...})
	/go/src/github.com/zricethezav/gitleaks/detect/detect.go:616 +0x3f8
github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles.func2()
	/go/src/github.com/zricethezav/gitleaks/detect/detect.go:506 +0x305
github.com/fatih/semgroup.(*Group).Go.func1()
	/go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0xa2
created by github.com/fatih/semgroup.(*Group).Go
	/go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x25b
```
I saw this error twice (i.e. when running Gitleaks on 2 different directories), but unfortunately I don't have a sample file to recreate this error.
