### ISSUE TITLE
Slice bounds out of range panic in v8.16.2

### ISSUE THREAD

**Issue by agmond** [gitleaks/gitleaks#1145]
Hi @zricethezav,

This issue is a reopening of https://github.com/gitleaks/gitleaks/issues/1132, since the fix in https://github.com/gitleaks/gitleaks/pull/1135 didn't solve the problem.

Here's what I see now (v8.16.2):
```
panic: runtime error: slice bounds out of range [31:28]

goroutine 185 [running]:
github.com/zricethezav/gitleaks/v8/detect.printFinding({{0xc0003b5b50, 0xf}, 0xd6, 0xd6, 0x16, 0x4b, {0xc00079b421, 0x1c}, {0xc00079b440, 0x1f}, ...}, ...)
	/go/src/github.com/zricethezav/gitleaks/detect/utils.go:131 +0x1575
github.com/zricethezav/gitleaks/v8/detect.(*Detector).addFinding(_, {{0xc0003b5b50, 0xf}, 0xd6, 0xd6, 0x16, 0x4b, {0xc00079b420, 0x1d}, {0xc00079b440, ...}, ...})
	/go/src/github.com/zricethezav/gitleaks/detect/detect.go:616 +0x3f8
github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectFiles.func2()
	/go/src/github.com/zricethezav/gitleaks/detect/detect.go:506 +0x305
github.com/fatih/semgroup.(*Group).Go.func1()
	/go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0xa2
created by github.com/fatih/semgroup.(*Group).Go
	/go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x25b
```
I saw this error twice (i.e. when running Gitleaks on 2 different directories), but unfortunately I don't have a sample file to recreate this error.

Thanks!

**Comment by rgmz** [comment]
I encountered this as well in #1141 and created PR #1143 as a proposed solution.
