### ISSUE TITLE
Gitleaks fails to run on ubuntu wsl with UrlError

### ISSUE THREAD

**Issue by bencipher** [gitleaks/gitleaks#1157]
**Describe the bug**
The pre-commit script for gitleaks is failing during commits with the error below 
`An unexpected error has occurred: URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it`

**To Reproduce**
pipenv install --dev pre-commit
pre-commit install
pre-commit autoupdate
git add .
git commit -m "updates to test gitleaks"

**Expected behavior**
I expected to see the report for gitleaks detailing the hardcoded credentials in my repo 
![image](https://user-images.githubusercontent.com/9444817/233416777-cd68cb0d-bfa6-4f55-85ee-a10f1f2601b0.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/9444817/233417218-944ef6c7-f3f8-46da-a58b-f3207265e1d9.png)

**Basic Info (please complete the following information):**
 - OS: Ubuntu on WSL
 - Gitleaks Version: v8.16.1, v8.16.3

**Additional context**
logs generated by pre-commit:
<details><summary>Logs</summary>
<p>

### version information

```
pre-commit version: 3.2.2
git --version: git version 2.39.0.windows.2
sys.version:
    3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
sys.executable: C:\Users\USER\.virtualenvs\app-UTkeMofs\Scripts\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
```

```
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1037, in _send_output
    self.send(msg)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 975, in send
    self.connect()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1447, in connect
    super().connect()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 941, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 851, in create_connection
    raise exceptions[0]
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\.virtualenvs\app-UTkeMofs\Lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File "C:\Users\USER\.virtualenvs\app-UTkeMofs\Lib\site-packages\pre_commit\main.py", line 381, in main
    return hook_impl(
           ^^^^^^^^^^
  File "C:\Users\USER\.virtualenvs\app-UTkeMofs\Lib\site-packages\pre_commit\commands\hook_impl.py", line 271, in hook_impl
    return retv | run(config, store, ns)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.virtualenvs\app-UTkeMofs\Lib\site-packages\pre_commit\commands\run.py", line 442, in run
    install_hook_envs(to_install, store)
  File "C:\Users\USER\.virtualenvs\app-UTkeMofs\Lib\site-packages\pre_commit\repository.py", line 248, in install_hook_envs
    _hook_install(hook)
  File "C:\Users\USER\.virtualenvs\app-UTkeMofs\Lib\site-packages\pre_commit\repository.py", line 95, in _hook_install
    lang.install_environment(
  File "C:\Users\USER\.virtualenvs\app-UTkeMofs\Lib\site-packages\pre_commit\languages\golang.py", line 137, in install_environment
    _install_go(version, env_dir)
  File "C:\Users\USER\.virtualenvs\app-UTkeMofs\Lib\site-packages\pre_commit\languages\golang.py", line 103, in _install_go
    resp = urllib.request.urlopen(_get_url(version))
                                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.virtualenvs\app-UTkeMofs\Lib\site-packages\pre_commit\languages\golang.py", line 97, in _get_url
    version = _infer_go_version(version)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\.virtualenvs\app-UTkeMofs\Lib\site-packages\pre_commit\languages\golang.py", line 90, in _infer_go_version
    resp = urllib.request.urlopen('https://go.dev/dl/?mode=json')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] No connection could be made because the target machine actively refused it>
```

</p>
</details> 

cc @zricethezav

**Comment by bencipher** [comment]
Nope, I am wfh using my PC and on the public internet of GLO

**Comment by zricethezav** [comment]
This is a pre-commit specific error. I don't have a solution but maybe someone in the community does. Thanks for trying to reproduce, @rgmz

**Comment by bencipher** [comment]
Alright, thanks but I should note that other hooks are running after I
commented out the gitleaks entry from my pre-commit-config.yml file. Thanks
again
